[PHEE-709] Create docker image for installing all dependencies for post-installation-job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,8 +5,60 @@ orbs:
   aws-eks: circleci/aws-eks@2.2.0
   kubernetes: circleci/kubernetes@1.3
   fynarfin-orb: fynarfin/docker-image-availability-check-and-upgrade@1.0.2
-
+executors:
+  docker-executor:
+    docker:
+      - image: circleci/openjdk:17-buster-node-browsers-legacy
 jobs:
+  build_and_push_post_installation_docker_image:
+    executor: docker-executor
+    environment:
+      JVM_OPTS: -Xmx512m
+      TERM: dumb
+    steps:
+      - checkout
+      # Install Docker to build and push the image
+      - setup_remote_docker:
+          version: 20.10.24
+
+      # Build the Docker image
+      - run:
+          name: Build Docker image
+          command: |
+            if [[ -n $(git show --name-only $CIRCLE_SHA1 | grep "^.circleci/Dockerfile") ]]; then
+              echo "Dockerfile has changed. Running the job."
+              docker build -t fynarfin/post-installation-job:latest .circleci
+              if [ "$CIRCLE_BRANCH" != "develop" ]; then
+                PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+                PR_TITLE=$(curl -sSL "https://api.github.com/repos/fynarfin/$CIRCLE_PROJECT_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+                JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+                if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY"; fi
+                docker image tag fynarfin/post-installation-job:latest fynarfin/post-installation-job:$JIRA_STORY
+              fi
+            else
+              echo "Dockerfile has not changed. Skipping the job."
+              circleci step halt
+            fi
+            
+
+      # Log in to DockerHub using environment variables
+      - run:
+          name: Login to DockerHub
+          command: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
+
+      # Push the Docker image to DockerHub
+      - run:
+          name: Push Docker image to DockerHub
+          command: |
+            if [ "$CIRCLE_BRANCH" = "develop" ]; then
+            docker push fynarfin/post-installation-job:latest
+            fi
+            if [ "$CIRCLE_BRANCH" != "develop" ]; then
+            PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+            PR_TITLE=$(curl -sSL "https://api.github.com/repos/fynarfin/$CIRCLE_PROJECT_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+            JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+            docker push fynarfin/post-installation-job:${JIRA_STORY}
+            fi
   build-g2p-sandbox-ci-chart:
     docker:
       - image: cimg/python:3.10
@@ -33,7 +85,7 @@ jobs:
                 if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY" && JIRA_STORY_DIR=$(echo /jira-story-version); fi
                 echo Charts will save in https://fynarfin.io/images/fynarfin$JIRA_STORY_DIR
             fi
-            CHART_URL="https://fynarfin.io/images/fynarfin$JIRA_STORY_DIR/ph-ee-g2p-sandbox-ci-0.0.0$JIRA_STORY"
+            CHART_URL="https://fynarfin.io/images/fynarfin$JIRA_STORY_DIR/ph-ee-g2psandbox-0.0.0$JIRA_STORY"
             if curl --output /dev/null --silent --head --fail "$CHART_URL"; then
               sed -i "11s@^ *repository:.*\$@  repository: $CHART_URL@" ph-ee-env-labs/helm/ph-ee-g2p-sandbox-ci/Chart.yaml
               sed -i "12s@^ *version:.*\$@  version: 0.0.0$JIRA_STORY@" ph-ee-env-labs/helm/ph-ee-g2p-sandbox-ci/Chart.yaml
@@ -572,6 +624,11 @@ jobs:
 workflows:
   deploy:
     jobs:
+      - build_and_push_post_installation_docker_image:
+          context:
+            - AWS
+            - slack
+            - DOCKER
       - build-and-host-engine:
           context:
             - AWS
@@ -612,3 +669,5 @@ workflows:
             - Ngrok
           requires:
             - build-g2p-sandbox-ci-chart
+            - build_and_push_post_installation_docker_image
+            - build-host-g2p-fyn-chart
